name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: fmt
      run: make fmt
    - name: vet
      run: make vet
    - name: test
      run: make test
    - name: build
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: build --clean --snapshot
